steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/tmp/animedigne:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/tmp/animedigne:latest",
      ]
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY